import os
from dotenv import load_dotenv

load_dotenv()


FINANCIAL_DATA_BASE_URL_STOCKS = os.getenv("FINANCIAL_DATA_BASE_URL_STOCKS")
FINANCIAL_DATA_API_KEY = os.getenv("FINANCIAL_DATA_API_KEY")

COIN_MARKET_CAP_CRYPTO_DATA_BASE_URL = os.getenv("COIN_MARKET_CAP_CRYPTO_DATA_BASE_URL")
COIN_MARKET_CAP_CRYPTO_API_KEY = os.getenv("COIN_MARKET_CAP_CRYPTO_API_KEY")
FOREX_RATE_API_KEY = os.getenv("FOREX_RATE_API")
FOREX_RATE_BASE_URL = os.getenv("FOREX_RATE_API_BASE_URL")
DEX_OPENROUTER_API_KEY = os.getenv("DEX_OPENROUTER_API_KEY")
